# Generated by Django 6.0.4 on 2026-05-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sufill X Man (Manknojiya Sufiyan)', max_length=200)),
                ('role', models.CharField(default='AI + Web + API Fullstack Developer', max_length=200)),
                ('phone', models.CharField(blank=True, default='7405721856', max_length=50)),
                ('email', models.EmailField(blank=True, default='sufillxman@gmail.com', max_length=254)),
                ('linkedin', models.URLField(blank=True, default='https://linkedin.com/in/sufill-x-man/')),
                ('github', models.URLField(blank=True, default='https://github.com/sufillxman')),
                ('instagram', models.URLField(blank=True, default='https://instagram.com/sufilldigital/')),
                ('summary', models.TextField(default='BCA student and fullstack builder creating automation-first web systems with Django, React and REST APIs.')),
                ('skills', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('highlights', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume Profile',
                'verbose_name_plural': 'Resume Profiles',
            },
        ),
    ]
